# Generated by .github/workflows/update-formula.yml. Do not edit by hand.
class Fianu < Formula
  desc "Fianu CLI — DevOps, gating, and security operations for the Fianu platform"
  homepage "https://fianu.io"
  version "1.9.73"

  on_macos do
    on_arm do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.73/cli_Darwin_arm64.tar.gz"
      sha256 "8d6a508e22e37ac9822a5279ca0b32230caad1f858794277672379394b2894d8"
    end
    on_intel do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.73/cli_Darwin_x86_64.tar.gz"
      sha256 "be350a6c507874d4576f4208a810c90b2661cdd3625e91b0c74b5009bfb6842b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.73/cli_Linux_arm64.tar.gz"
      sha256 "b874de888925cb6529450ddac8504b48bbb1c13dc81323ffe50b485028465e16"
    end
    on_intel do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.73/cli_Linux_x86_64.tar.gz"
      sha256 "7d9504edd371be18f1c1a6aaf5e954babfe8527cfca36d3dc0f59720d354d2f1"
    end
  end

  def install
    bin.install "cli" => "fianu"
  end

  test do
    system "#{bin}/fianu", "version"
  end
end
