# Generated by .github/workflows/update-formula.yml. Do not edit by hand.
class Fianu < Formula
  desc "Fianu CLI — DevOps, gating, and security operations for the Fianu platform"
  homepage "https://fianu.io"
  version "1.9.79"

  on_macos do
    on_arm do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.79/cli_Darwin_arm64.tar.gz"
      sha256 "b3e029c2380ca2a885a1dda057e3b7c617657e394e0219a2b27b28986bd3f6c1"
    end
    on_intel do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.79/cli_Darwin_x86_64.tar.gz"
      sha256 "1ca76612154c918257f09f923c63f879f6338a91616a072ab082b83a1c40d627"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.79/cli_Linux_arm64.tar.gz"
      sha256 "2811968d32dc7e5ba624cb2db4b29aaa1c59f75f39a72af46c785d7817fc58d7"
    end
    on_intel do
      url "https://github.com/fianulabs/homebrew-tap/releases/download/v1.9.79/cli_Linux_x86_64.tar.gz"
      sha256 "aff60ad381feb0e3c3f9e9b2dfe267c7db2f44caa10d1acbbedaa71d44f8397a"
    end
  end

  def install
    bin.install "cli" => "fianu"
  end

  test do
    system "#{bin}/fianu", "version"
  end
end
